name: CI/CD Pipeline for MSS

on:
  push:
    branches:
      - master
   
  pull_request:
    branches:
      - master

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install unzip
      - name: Install unzip
        run: sudo apt-get install -y unzip 
        
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Build Project with NPM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test

      # Install SonarScanner
      - name: Install SonarScanner
        run: |
          wget -qO- https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -O /tmp/sonar-scanner.zip
          unzip /tmp/sonar-scanner.zip -d /tmp
          echo "/tmp/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      # SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Nodejs-MSS \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://54.196.147.196:9000 \
            -Dsonar.login=$SONAR_TOKEN
            
       # Upload Node.js Artifact to Nexus
      - name: Upload Node.js Artifact to Nexus
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          # Get the name of the generated artifact
          ARTIFACT=$(ls *.tgz)

          # Upload the artifact to Nexus
          curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD \
          --upload-file $ARTIFACT \
          $NEXUS_URL/repository/your-repo-name/$ARTIFACT

        # Run the Node.js Application
        - name: Run Node.js App
          run: |
          # Run the Node.js application
          npm start
